export const DARK_THEME_ACTIVE = 'DARK_THEME_ACTIVE';
export const DARK_THEME_INACTIVE = 'DARK_THEME_INACTIVE';
export const SIGNED_IN_SUCCEEDED = 'SIGNED_IN_SUCCEEDED';
export const RESET_SIGNED_IN_SUCCEEDED = 'RESET_SIGNED_IN_SUCCEEDED';
export const USER_INFO = 'USER_INFO';
export const MILITARY_VERSION = 'MILITARY_VERSION';
export const SPORTS_VERSION = 'SPORTS_VERSION';

